name: tic_tac_toe
description: Functional Tic Tac Toe game with tests.
version: 1.0.0
homepage: https://github.com/Mhwmd/tic-tac-toe

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
